apiVersion: v1
kind: PersistentVolume
metadata:
  name: classedge-pv
  namespace: classedge
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/classedge-storage  # 워커 노드의 실제 경로

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: classedge-pvc
  namespace: classedge
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: classedge-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classedge-api-deploy
  namespace: classedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classapi-pod
  template:
    metadata:
      labels:
        app: classapi-pod
    spec:
      containers:
        - name: classapi-container
          image: jaechang13/classedgeapi:33efb40edbeeab47581a5bea2e1e858ea2beeab2
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: upload-storage
              mountPath: /home/user1/upload  # 스프링부트 설정에서 지정한 경로
      volumes:
        - name: upload-storage
          persistentVolumeClaim:
            claimName: classedge-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: classedge-service
  namespace: classedge
spec:
  selector:
    app: classapi-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32080
  type: NodePort
